#!/bin/bash

CMAKE_VERSION=$1

apt-get install cmake

# CMake 20.10'u indirin ve açın
curl -OL https://github.com/Kitware/CMake/releases/download/v$CUDA_VERSION/cmake-$CUDA_VERSION-SHA-256.txt
curl -OL https://github.com/Kitware/CMake/releases/download/v$CUDA_VERSION/cmake-$CUDA_VERSION.tar.gz
sha256sum -c --ignore-missing cmake-$CUDA_VERSION-SHA-256.txt
tar -xzvf cmake-$CUDA_VERSION.tar.gz

# cmake-3.20.0 klasörüne gidin
cd cmake-$CMAKE_VERSION

cmake .
make      
make install