#!/bin/bash

CMAKE_VERSION=$1

apt-get install cmake

# CMake 20.10'u indirin ve açın
wget https://cmake.org/files/v3.20/cmake-3.20.0.tar.gz
tar -xzvf cmake-3.20.0.tar.gz

# cmake-3.20.0 klasörüne gidin
cd cmake-3.20.0

# cmake-3.20.0'u yapılandırın
./bootstrap

# cmake-3.20.0'u derleyin ve yükleyin
make -j$(nproc)
sudo make install