#!/bin/bash

OPENCV_VERSION=$1
CUDA_VERSION=$2

apt-get install python3-numpy -y

wget -O opencv.zip https://github.com/opencv/opencv/archive/$OPENCV_VERSION.zip
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/$OPENCV_VERSION.zip
unzip opencv.zip
unzip opencv_contrib.zip
mv opencv_contrib-$OPENCV_VERSION opencv_contrib
mv opencv-$OPENCV_VERSION opencv
cd opencv
mkdir -p build && cd build
cmake ..
#To-Do: buraya cuda ile derleme gelecek
make -j`nproc`
make install